### ISSUE TITLE
Support for Index 2017-43

### ISSUE THREAD

**Issue by fizerkhan** [CI-Research/KeywordAnalysis#1]
I got following error when I tried to download index `2017-43`. `CDXItem.java` does not understand the field `mime-detected`. Can you please fix it?

I run this command `./gradlew downloadDocuments`

```
2017-10-30 06:35:53 INFO    [DownloadFromCommonCrawl] Downloading line 1: 0.0000%, having 0 downloaded: {"urlkey": "io,freshsales)/", "timestamp": "2017082...
Exception in thread "main" java.lang.IllegalStateException: Unknown field found: mime-detected
        at org.dstadler.commoncrawl.index.CDXItem.parse(CDXItem.java:60)
        at org.dstadler.commoncrawl.index.DownloadFromCommonCrawl.main(DownloadFromCommonCrawl.java:43)
:downloadDocuments FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':downloadDocuments'.
> Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 1
```

**Comment by nelsonjiao** [comment]
Common Crawl changed their data set parameter recently. We have updated our code, it should work now.
